export const jokes = [
  "🐛 Pourquoi le développeur porte-t-il des lunettes ? Parce qu'il ne voit pas ses bugs à l'œil nu.",
  "« Ça marche chez moi. » — La phrase officielle avant un incident de production.",
  "Un bug entre dans un bar. Le barman dit : « Désolé, on ne sert pas les bugs. » Le bug répond : « Pourtant, je suis en production. »",
  "Le développeur a trouvé un bug. Il l'a corrigé. Trois nouveaux sont apparus. La nature reprend ses droits.",
  "Pourquoi les bugs sont-ils toujours en retard ? Parce qu'ils attendent la production.",
  "Le debugger demande : « Où est le problème ? » Le code répond : « C'est compliqué. »",
  "J'ai corrigé un bug sans comprendre pourquoi. Maintenant j'ai peur de toucher au code.",
  "Le vrai développeur ne supprime jamais un bug : il lui donne un nom.",
  "« Ce bug est impossible. » — Phrase prononcée juste avant de trouver le bug.",
  "Mon code n'a pas de bugs. Il a des fonctionnalités surprises.",
  "Un bug peut rester caché pendant six mois. Il suffit qu'un client clique dessus une fois.",
  "Pourquoi les bugs aiment-ils les développeurs ? Parce qu'ils leur donnent beaucoup d'attention.",
  "J'ai passé quatre heures à chercher un bug. C'était une faute de frappe.",
  "Le bug : « Tu ne me trouveras jamais. » Le développeur : « J'ai console.log. »",
  "Debugger, c'est comme être détective dans un film où tu es aussi celui qui a commis le crime.",
  "Mon debugger et moi avons une relation toxique : il me montre mes erreurs.",
  "Un développeur voit un bug. Il ajoute un console.log. Le bug déménage.",
  "« Pourquoi ça plante ? » « Parce que ça fonctionne. »",
  "Le bug n'était pas dans le code. Il était entre le clavier et la chaise.",
  "Quand tu corriges un bug à 2 h du matin, chaque ligne devient suspecte.",
  "🌳 Git est simple : tu fais un commit et tu pries.",
  "git push : confiance. git push --force : courage.",
  "Pourquoi Git est-il romantique ? Parce qu'il permet de revenir dans le passé.",
  "« Qui a supprimé cette fonction ? » — « Je sais pas. Regarde Git. »",
  "Git : « Tu veux fusionner ? » Développeur : « Oui. » Git : « Conflit. »",
  "Un conflit Git, c'est deux développeurs qui pensent avoir raison avec des preuves.",
  "git pull : « Je récupère le travail des autres. »",
  "git push : « Maintenant, ils vont récupérer le mien. »",
  "Le développeur qui n'a jamais fait de git reset --hard n'a jamais vraiment vécu.",
  "git status : le bulletin scolaire du développeur.",
  "Mon historique Git ressemble à mon historique de décisions : compliqué.",
  "Pourquoi Git est-il mauvais en cuisine ? Parce qu'il fait beaucoup de merges.",
  "« Fais un commit propre. » — « Je suis développeur, pas magicien. »",
  "git blame : le bouton officiel pour chercher un coupable.",
  "Git blame : « Ce n'est pas moi, c'est lui. »",
  "Le meilleur outil de gestion de projet : git blame.",
  "Quand Git dit « Already up to date », tu te demandes immédiatement ce que tu as oublié.",
  "git merge : le moment où deux branches deviennent une thérapie de groupe.",
  "« Ça marche sur ma branche. » — C'est donc officiellement ton problème.",
  "Le développeur : « Je vais juste regarder le diff. » Deux heures plus tard : architecture complète refondue.",
  "☕ Combien de cafés faut-il à un développeur ? Un de plus que le nombre disponible.",
  "Le café est une dépendance. Le code est une conséquence.",
  "Sans café, mon IDE est plus rapide que moi.",
  "Le développeur ne dort pas : il attend que le build termine.",
  "« Tu travailles depuis combien de temps ? » « Depuis que j'ai ouvert VS Code. »",
  "Le développeur est une créature nocturne qui se nourrit de café et de stack traces.",
  "Pourquoi les développeurs aiment la nuit ? Parce que personne ne demande « ça avance ? »",
  "Le développeur : « Je finis juste cette fonction. »",
  "La fonction : 14 dépendances, 3 refactorings et une crise existentielle.",
  "Mon IDE connaît mieux ma vie que ma famille.",
  "J'ai demandé une pause à mon code. Il m'a donné une exception.",
  "Le développeur ne procrastine pas. Il fait du refactoring préventif.",
  "Une réunion de 30 minutes peut généralement être remplacée par trois lignes de code.",
  "Mais trois lignes de code peuvent aussi créer trois jours de réunions.",
  "Le meilleur moment pour documenter le code ? Hier.",
  "Le deuxième meilleur moment ? Quand quelqu'un demande pourquoi ça fonctionne.",
  "« C'est temporaire. » — Le commentaire qui fête bientôt ses dix ans.",
  "Le développeur commence sa journée avec une TODO et la termine avec une TODO différente.",
  "Mon planning est comme mon code : optimiste et totalement faux.",
  "Le développeur connaît deux états : « ça marche » et « pourquoi ça marche ? »",
  "Quand un développeur dit « facile », méfie-toi.",
  "☕ Pourquoi Java porte-t-il des lunettes ? Parce qu'il ne voit pas ses classes.",
  "Java : écrire 40 lignes pour dire bonjour depuis 1995.",
  "Java voulait être simple. Puis il a rencontré les design patterns.",
  "En Java, même une erreur a une classe.",
  "Pourquoi Java n'aime pas les vacances ? Parce qu'il doit toujours faire tourner la JVM.",
  "Un développeur Java entre dans un bar. Il demande une bière. Le serveur lui donne un objet Beer.",
  "Java : « Write once, run anywhere. »",
  "JavaScript : « Write once, debug everywhere. »",
  "La JVM ne dort jamais. Elle fait du garbage collection.",
  "Java et JavaScript se ressemblent autant que car et carpet.",
  "Le développeur Java ne dit jamais « variable ». Il dit « instance mutable ».",
  "🐍 Pourquoi Python est-il populaire ? Parce qu'il aime les serpents et les débutants.",
  "Python : « Je peux tout faire. »",
  "Développeur : « Même mon café ? »",
  "Python : « Installe un package. »",
  "En Python, l'indentation est une question de survie.",
  "Un développeur Python entre dans un bar. Il trouve une erreur d'indentation et repart.",
  "Pourquoi Python est-il calme ? Parce qu'il garde toujours son zen.",
  "Python n'a pas de problèmes. Il a des exceptions.",
  "pip install : le début d'une aventure dont personne ne connaît la fin.",
  "Python : simple à écrire, mystérieux à déployer.",
  "« Ça marche avec Python 3.11. » — Dernières paroles avant le Dockerfile.",
  "Mon code Python est propre. Il est juste… fonctionnellement désordonné.",
  "🟨 JavaScript : le seul langage où [] + [] peut devenir une discussion philosophique.",
  "Pourquoi JavaScript est-il flexible ? Parce qu'il accepte presque tout.",
  "JavaScript ne fait pas d'erreurs. Il fait des surprises.",
  "undefined est probablement la variable la plus honnête du langage.",
  "JavaScript : « Tu veux un entier ? »",
  "Développeur : « Oui. »",
  "JavaScript : « NaN. »",
  "Pourquoi JavaScript est-il comme un magicien ? Parce qu'il transforme des choses en d'autres choses sans prévenir.",
  "== : « On peut s'arranger. »",
  "=== : « On vérifie les papiers. »",
  "Le développeur JS voit null et undefined. Il commande un café.",
  "Promesse JavaScript : « Je te répondrai plus tard. »",
  "async/await : parce qu'attendre était devenu une fonctionnalité.",
  "JavaScript : le langage où une petite modification peut casser Internet.",
  "« J'ai juste changé le CSS. »",
  "JavaScript : « Intéressant. »",
  "React : écrire du HTML pour faire du JavaScript pour afficher du HTML.",
  "Redux : parce qu'un simple objet n'était apparemment pas suffisant.",
  "NPM : télécharger Internet, une dépendance à la fois.",
  "node_modules : le dossier qui pèse plus lourd que ton projet.",
  "Pourquoi node_modules est-il si gros ? Parce qu'il contient les dépendances des dépendances des dépendances.",
  "npm install : « Ça prendra une minute. »",
  "17 minutes plus tard.",
  "JavaScript a tellement de frameworks que choisir en est devenu un framework.",
  "Le développeur JS ne demande pas « pourquoi ? » Il demande « dans quel navigateur ? »",
  "🐧 Linux : où tout est fichier, y compris tes problèmes.",
  "Un utilisateur Windows demande : « Pourquoi utiliser Linux ? »",
  "Le développeur répond : « Parce que je peux. »",
  "sudo : le mot magique qui transforme un utilisateur en administrateur.",
  "Linux ne plante pas. Il t'offre une expérience pédagogique.",
  "« Je vais juste modifier ce fichier système. »",
  "Linux : « Vas-y, champion. »",
  "Pourquoi les Linuxiens aiment le terminal ? Parce qu'il ne leur pose pas de questions inutiles.",
  "chmod 777 : quand tu ne sais pas quoi faire mais que tu veux que ça marche.",
  "Le terminal : trois commandes et tu te sens hacker.",
  "rm -rf : deux secondes pour exécuter, trois heures pour regretter.",
  "Linux : « Tu veux une interface graphique ? »",
  "Développeur : « Pourquoi ? »",
  "Le pingouin n'a pas peur des bugs. Il les met en production.",
  "Bash : parce que cliquer, c'est surfait.",
  "grep : Google, mais pour les fichiers.",
  "man : Google, mais sans Internet.",
  "ls : la façon Linux de demander « qu'est-ce que j'ai cassé ? »",
  "🗄️ Pourquoi SQL est-il mauvais en couple ? Parce qu'il préfère les relations.",
  "SQL adore les relations, mais déteste les conflits.",
  "SELECT * FROM life WHERE happiness = true;",
  "Résultat : 0 lignes.",
  "Le développeur SQL entre dans un bar et demande une table.",
  "SQL : « Je connais toutes tes relations. »",
  "Pourquoi SQL est-il indiscret ? Parce qu'il fait toujours des SELECT.",
  "DELETE FROM stress;",
  "Erreur : permission denied.",
  "DROP TABLE users;",
  "DBA : « TU AS FAIT QUOI ?! »",
  "Un JOIN entre dans un bar. Il repart avec deux tables.",
  "Pourquoi le DBA dort mal ? Parce qu'il rêve de backups.",
  "Les bases de données ont deux états : sauvegardées et « j'espère que quelqu'un a sauvegardé ».",
  "Un bon DBA fait des backups. Un excellent DBA vérifie les backups.",
  "NULL : ni vrai, ni faux, ni vraiment là.",
  "SQL n'est pas compliqué. C'est juste une langue où une faute peut supprimer 10 millions de lignes.",
  "« Je vais optimiser cette requête. »",
  "Deux heures plus tard : « J'ai réinventé la base de données. »",
  "🌐 HTTP 404 : même Internet ne sait pas où est le fichier.",
  "HTTP 500 : « Ce n'est pas toi, c'est moi. »",
  "HTTP 401 : « Tu n'es pas qui tu prétends être. »",
  "HTTP 403 : « Je sais qui tu es. Non. »",
  "HTTP 200 : le petit voyant vert de l'âme du développeur.",
  "Le navigateur : « CSS ? »",
  "CSS : « Ça dépend du navigateur. »",
  "Pourquoi CSS est-il difficile ? Parce que centrer une div est une compétence légendaire.",
  "Le développeur qui réussit à centrer une div du premier coup reçoit une médaille.",
  "HTML : « Je structure. »",
  "CSS : « Je décore. »",
  "JS : « Je casse. »",
  "Le frontend : « C'est joli. »",
  "Le backend : « Ça fonctionne. »",
  "Le client : « Je veux autre chose. »",
  "Pourquoi le frontend déteste le backend ? Parce que le backend renvoie toujours un JSON différent.",
  "CORS : la façon polie d'un navigateur de dire « non ».",
  "Cookies : parce qu'Internet avait besoin de miettes.",
  "Le développeur web ne perd jamais son chemin : il suit les redirects.",
  "Une API entre dans un bar. Elle répond avec un 404.",
  "🧠 J'ai demandé à une IA de coder. Elle a créé une réunion.",
  "L'IA écrit du code plus vite que moi. Heureusement, je sais où sont les bugs.",
  "« Pourquoi ton code est-il si compliqué ? »",
  "« L'IA l'a optimisé. »",
  "L'IA : « Voici une solution élégante. »",
  "Développeur : « Elle compile ? »",
  "IA : « Élégante. »",
  "Prompt : « Écris un programme simple. »",
  "IA : importe 37 bibliothèques.",
  "L'IA ne remplace pas le développeur. Elle remplace surtout son sommeil.",
  "Un développeur et une IA entrent dans un bar. L'IA commande 10 000 tokens.",
  "« L'IA hallucine. »",
  "« Moi aussi quand je regarde mon code à 3 h du matin. »",
  "Chatbot : « Je peux vous aider. »",
  "Développeur : « Explique-moi pourquoi mon code marche. »",
  "IA : « Je ne peux pas savoir. »",
  "Développeur : « Enfin une réponse honnête. »",
  "🧪 Pourquoi écrire des tests ? Pour savoir exactement comment ton code va casser.",
  "Test unitaire : « Je vérifie une petite chose. »",
  "Test d'intégration : « Je vérifie pourquoi tout le reste est cassé. »",
  "Test end-to-end : « Je vérifie que l'utilisateur souffre correctement. »",
  "Le développeur écrit un test. Le code commence immédiatement à se comporter correctement par peur.",
  "« Tous les tests passent ! »",
  "Production : « C'est adorable. »",
  "Un test flaky n'est pas un bug. C'est un test qui a une personnalité.",
  "Le test échoue uniquement en CI. Évidemment.",
  "CI : « It works on my machine » n'est pas une excuse.",
  "Le développeur : « Je vais désactiver ce test temporairement. »",
  "Trois ans plus tard.",
  "🚀 DevOps : quand le développeur découvre que quelqu'un doit maintenir son code.",
  "Docker : « Ça marche sur ma machine. »",
  "Docker : « Maintenant ça marche dans mon conteneur. »",
  "Kubernetes : parce qu'un serveur ne suffisait pas pour faire compliqué.",
  "Pourquoi Kubernetes est-il difficile ? Parce que même son logo ressemble à une énigme.",
  "CI/CD : Continuous Integration / Continuous Déception.",
  "Pipeline : « Tout est vert ! »",
  "Production : « Non. »",
  "Déployer vendredi soir : parce que les week-ends sont surfaits.",
  "Le serveur tombe à 17h59. Le développeur : « Je savais que j'aurais dû prendre des vacances. »",
  "Monitoring : découvrir que le système est cassé grâce à un graphique.",
  "Alerting : recevoir 347 notifications pour une seule erreur.",
  "Le DevOps dort avec son téléphone sous l'oreiller.",
  "Kubernetes : Docker, mais avec un doctorat.",
  "Cloud : l'ordinateur de quelqu'un d'autre, mais avec une facture.",
  "Serverless : des serveurs qui existent toujours, mais que tu ne peux pas regarder.",
  "🤓 Un développeur entre dans un bar avec 1 bière, 2 bières, 0 bière, -1 bière et 999999999 bières. Le barman ferme le bar.",
  "Le programmeur demande à sa femme : « Tu veux du lait ? » Elle répond oui. Il revient avec 10 litres.",
  "Pourquoi les développeurs aiment Halloween ? Parce que if et else sont leurs costumes préférés.",
  "Un développeur voit une ampoule cassée. Il dit : « Ça marche chez moi. »",
  "Pourquoi les programmeurs confondent Halloween et Noël ? Parce que OCT 31 == DEC 25.",
  "Un développeur ne fait pas de régime. Il optimise ses calories.",
  "« Tu fais quoi dans la vie ? »",
  "« Je transforme des problèmes simples en problèmes avec des dépendances. »",
  "Le développeur n'est pas antisocial. Il préfère les interfaces bien documentées.",
  "Mon langage préféré ? Celui qui ne me fait pas écrire de code.",
  "Pourquoi les développeurs sont-ils mauvais en géographie ? Parce qu'ils pensent que tout est relatif.",
  "Le développeur aime les fonctions courtes. Sauf quand il écrit la fonction.",
  "« C'est du legacy. »",
  "Traduction : « Personne ne sait comment ça marche. »",
  "Le legacy code est comme un vieux château : magnifique, mystérieux et surtout ne touche à rien.",
  "Refactoring : changer tout sans changer ce que ça fait.",
  "Optimisation prématurée : résoudre un problème que personne n'avait encore.",
  "Le développeur : « Je vais documenter ça. »",
  "Son cerveau : « Tu vas te souvenir. »",
  "La documentation : toujours à jour, sauf quand tu en as besoin.",
  "Stack Overflow : là où les développeurs vont chercher la phrase exacte qu'ils doivent copier.",
  "Le développeur senior : « Ne touche pas à ça. »",
  "Le junior : « Pourquoi ? »",
  "Senior : « Parce que je l'ai déjà fait. »",
  "Le développeur parfait n'existe pas. Mais il est probablement en train de corriger un bug qui prétend ne pas exister.",
  "Pourquoi les développeurs confondent Halloween et Noël ? Parce que OCT 31 = DEC 25. 🎃🎄",
  "Le code d’hier était propre, élégant et parfaitement compréhensible. Je ne sais pas qui l’a écrit, mais je le déteste.",
  "J’ai passé la journée à écrire du code pour automatiser une tâche de 30 secondes. Maintenant, la tâche prend 5 minutes, mais elle est automatique.",
  "J’ai corrigé un bug sans en créer un autre. Je vais probablement raconter cette histoire à mes petits-enfants.",
  "« On déploie vendredi, ça devrait aller. » Phrase prononcée juste avant chaque catastrophe.",
  "J’ai corrigé un bug et maintenant j’en ai trois, la productivité est au rendez-vous. 🐛",
  "Mon code est tellement optimisé qu’il plante beaucoup plus rapidement. ⚡"
]

export function getRandomJoke(): string {
  const randomIndex = Math.floor(Math.random() * jokes.length)
  return jokes[randomIndex]
}
